// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8rlhPzfbkGx5wAAYOAkFxH7360EPjQpY',
    appId: '1:298777870354:web:8a7d5fbc90f688a1f898cb',
    messagingSenderId: '298777870354',
    projectId: 'flutter-ml-c69c1',
    authDomain: 'flutter-ml-c69c1.firebaseapp.com',
    storageBucket: 'flutter-ml-c69c1.appspot.com',
    measurementId: 'G-39ZW8LMLWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxUmejXWjxLwaOgtw8u90xlkRaznRkLBo',
    appId: '1:298777870354:android:6abdb9bc21b0ca30f898cb',
    messagingSenderId: '298777870354',
    projectId: 'flutter-ml-c69c1',
    storageBucket: 'flutter-ml-c69c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNXs-W2WERkcPhfNHEnGg5LgryslF2N7k',
    appId: '1:298777870354:ios:259ff09f2635a59cf898cb',
    messagingSenderId: '298777870354',
    projectId: 'flutter-ml-c69c1',
    storageBucket: 'flutter-ml-c69c1.appspot.com',
    androidClientId: '298777870354-kr6fc54chqulsvgv6pprodqd0nl9rrka.apps.googleusercontent.com',
    iosClientId: '298777870354-p9u63mvq76r45rip28u8bctlp9k4fuar.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNXs-W2WERkcPhfNHEnGg5LgryslF2N7k',
    appId: '1:298777870354:ios:259ff09f2635a59cf898cb',
    messagingSenderId: '298777870354',
    projectId: 'flutter-ml-c69c1',
    storageBucket: 'flutter-ml-c69c1.appspot.com',
    androidClientId: '298777870354-kr6fc54chqulsvgv6pprodqd0nl9rrka.apps.googleusercontent.com',
    iosClientId: '298777870354-p9u63mvq76r45rip28u8bctlp9k4fuar.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
